runtime: nodejs22

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "22"

vpc_access_connector:
    name: projects/capstone-entertainme/locations/asia-southeast2/connectors/mysql-connector